### ISSUE TITLE
【提问】{代理端口}

### ISSUE THREAD

**Issue by wanghaisheng** [Nemo2011/bilibili_api#6]
**Python 版本：** 3.x

**模块版本：** x.x.x

**运行环境：** Windows / Linux

---

```
Traceback (most recent call last):
  File ".\bilisearch.py", line 175, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "D:\Program Files\anaconda3\envs\autopub\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File ".\bilisearch.py", line 158, in main
    r = await misc.web_search_by_type(k,'video')
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\bilibili_api\misc.py", line 36, in web_search_by_type
    return await request('GET', url=api["url"], params=params)
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\bilibili_api\utils\network.py", line 111, in request
    async with session.request(**config) as resp:
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\aiohttp\connector.py", line 1073, in _create_proxy_connection
    transport, proto = await self._create_direct_connection(
  File "D:\Program Files\anaconda3\envs\autopub\lib\site-packages\aiohttp\connector.py", line 1011, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host {proxy}:80 ssl:default [getaddrinfo failed]
```

        proxypool='https://proxypool.scrape.center/random'

        proxy = requests.get(proxypool).text
        print(proxy,'========')
        settings.proxy = "http://{proxy}" # 里头填写你的代理地址
        r = await misc.web_search_by_type(k,'video')

**Comment by Nemo2011** [comment]
对不起，能不能发一下代理网址，还有运行时究竟是 Windows 上报错还是 Linux 报错（就是用的是 Linux 运行还是 Windows 运行），蟹蟹。

**Comment by wanghaisheng** [comment]
https://proxypool.scrape.center/random 就是这个啊
windows

**Comment by Nemo2011** [comment]
- 1. 你可以访问一下你的代理网址，上面只是返回一个可以用的代理网址，那个网址只是 API，真正的 API 需要自己爬取
- 2. 我发现，aiohttp 的代理支持是真的 TM 的懒，现在正在测试代理，再稍等几天新版本会发布，问题就应该解决了，请耐心等待。
- 3. 用代理时先测试一下，不要到时候没法用。
